### ISSUE TITLE
Bee piece did not show up and could be overwritten

### ISSUE THREAD

**Issue by olsson22** [liuer21/Hive#10]
Bug report by Fredrik Olsson:
1. placed a bee piece on (3,6)
2. Bee piece did not show up
3. I then played a spider on (3,6) and the icon of the spider showed up on spot (3,6)

**Comment by TheCoolBoss** [comment]
If the buttons were used to attempt to place the piece, there is only one bee allowed, meaning a second cannot be placed. Multiple spiders are allowed, so placing more than one is legal.

**Comment by hilderbr21** [comment]
Only one bee from each color can be on the board at a time. Since we haven't removed the bees from the starting board yet, this sounds like it is working as intended.
