### ISSUE TITLE
Must press bug-type button for every move

### ISSUE THREAD

**Issue by ghost** [liuer21/Hive#12]
I'm not sure if this is supposed to behave this way, or y'all just haven't implemented this feature yet. However, in order to place a bug tile, one must always press one of the bug-type buttons before placing a tile. It might be nicer if that information were to be saved, such that when placing the same bug tile repeatedly, one wouldn't have to repeatedly choose that bug-type. For example, if I wanted to place five spiders, I could press the spider button, and then tap the board five times, instead of having to press the spider button five times as well.

**Comment by hilderbr21** [comment]
Only one action is allowed per turn. If a player chooses to place a bug, they can only place one bug and their turn ends. On the other hand if a player chooses to move a piece, they cannot place a bug. As of the time of this comment, the player is not locked out of making a move while waiting for the AI's turn.
