### ISSUE TITLE
Blank hexagons don't disappear when reset button is pressed.

### ISSUE THREAD

**Issue by daniel-c-dev** [liuer21/Hive#3]
1. Tap to select a piece and tap to place the piece.
2. Tap a location adjacent to the piece to move it.
3. Press reset button.
4. The blank hexagons leftover after moving the piece still remain.
5. Some pieces don't get placed after reset.

**Comment by hilderbr21** [comment]
The leftover blank hexagons have been fixed. Not sure about your issue where pieces that don't get placed after reset. It might be attributable to limits on number of pieces that can be placed. Per player there can be only one bee, two spiders, two beetles, three ants, and three grasshoppers placed on the board.
