### ISSUE TITLE
Highlights on empty board

### ISSUE THREAD

**Issue by hilderbr21** [liuer21/Hive#32]
After a reset, tap button to place, entire board becomes targeted.
tap button again to deselect, and tap one more time to select piece to place.

Bug: Entire board does not become targeted after second selection (but it can still be placed.)

**Comment by TheCoolBoss** [comment]
Will not fix: the entire board highlight is mostly for enhancement purposes and is not part of the core gameplay.  It is also quite slow and may be detrimental to experience if buttons are constantly tapped and untapped.
