### ISSUE TITLE
Placing Bee Piece

### ISSUE THREAD

**Issue by nieland22** [liuer21/Hive#7]
Bug Report by Sierra Nieland: 
1. Placed pieces initially. 
2. Tried to place the bee on the board. 
3. The bee piece did not show up.
4. Blank piece showed up where the bee was placed after placing a different piece. 
5. New piece was able to be placed in the blank hexagon where the bee was originally placed.

**Comment by hilderbr21** [comment]
-Second bee is not supposed to be placed
-blank hexagon after piece is moved is a known issue (separate bug)
